import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Container, Text } from "@nextui-org/react";

const Location: NextPage = () => {

	return (
		<>
			<Head>
				<title>URL Shortener</title>
				<meta content="Generated by create next app" name="description" />
				<link href="/favicon.ico" rel="icon" />
			</Head>
			<Container>
				<Text>Hola</Text>
			</Container>
		</>
	);
};

export default Location;
